CREATE TABLE "public"."prompts" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "theme"      text                     NOT NULL,
  "text"       text                     NOT NULL,
  "language"   text                     NOT NULL,
  CONSTRAINT "prompts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."prompts"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."prompts"
  FOR SELECT
  TO PUBLIC
  USING (true);

COMMENT ON TABLE "public"."prompts" IS 'Speaking prompts available in Parlons';

REVOKE ALL ON SEQUENCE "public"."prompts_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."prompts_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."prompts_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."prompts_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."prompts_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."prompts_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."prompts_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."prompts_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."prompts" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."prompts" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."prompts" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."prompts" TO "service_role";

