-- Relational model for prompts: languages and themes become their own tables.
-- The legacy prompts.language and prompts.theme text columns are kept and will
-- be dropped in a later cleanup migration, after the app has been switched over.

-- 1. Lookup tables ----------------------------------------------------------

create table public.languages (
  id   bigint generated by default as identity primary key,
  code text not null unique,
  name text not null
);

create table public.themes (
  id   bigint generated by default as identity primary key,
  key  text not null unique,
  name text not null
);

comment on table public.languages is 'Languages prompts can be written in (code is e.g. en, fr)';
comment on table public.themes is 'Language-independent conversation themes';

-- 2. Seed from existing prompt values ---------------------------------------

insert into public.languages (code, name)
select distinct
  p.language,
  case p.language
    when 'en' then 'English'
    when 'fr' then 'French'
    else p.language
  end
from public.prompts p;

-- Theme keys are canonical, language-independent identifiers, so they are
-- seeded explicitly rather than copied from the legacy prompts.theme values.
insert into public.themes (key, name) values
  ('technology', 'Technology'),
  ('work',       'Work'),
  ('travel',     'Travel');

-- 3. Relationship columns on prompts ----------------------------------------

alter table public.prompts
  add column language_id bigint references public.languages (id),
  add column theme_id    bigint references public.themes (id);

update public.prompts p
set language_id = l.id
from public.languages l
where l.code = p.language;

-- Map each legacy theme value to its canonical theme key. The legacy
-- prompts.theme column itself is left unchanged.
update public.prompts p
set theme_id = t.id
from (values
  ('technology', 'technology'),
  ('travail',    'work'),
  ('voyage',     'travel')
) as m (legacy_theme, theme_key)
join public.themes t on t.key = m.theme_key
where m.legacy_theme = p.theme;

-- 4. Enforce the relationship after the backfill ----------------------------
-- These fail (and roll the whole migration back) if any row was left unmatched.

alter table public.prompts
  alter column language_id set not null,
  alter column theme_id    set not null;

create index prompts_language_id_idx on public.prompts (language_id);
create index prompts_theme_id_idx    on public.prompts (theme_id);

-- 5. RLS: public read-only content ------------------------------------------

alter table public.languages enable row level security;
alter table public.themes    enable row level security;

create policy "Enable read access for all users" on public.languages
  for select
  to anon, authenticated
  using (true);

create policy "Enable read access for all users" on public.themes
  for select
  to anon, authenticated
  using (true);
